services:
  orchestrator:
    container_name: orchestrator
    build: 
      context: src/PC4
      dockerfile: Dockerfile
    environment:
      WORKER_TYPE: "orchestrator"
      WORKER_PORT: "8040"
      API_PORT: "8080"
      MONGODB_URI: "mongodb://user:pass@mongo:27017"
      REDIS_ADDR: "redis:6379"
      MOVIE_CSV_PATH:  "/data/csv/movies.csv"
      RATING_CSV_PATH: "/data/csv/ratings.csv"
      TAGS_CSV_PATH:   "/data/csv/tags.csv"
      LINKS_CSV_PATH:   "/data/csv/links.csv"
      FILL_DB:   "False"
      JWT_SECRET: "ed8ce1ddee2d90ecff7c9f7972296399d922a7749a121aba6286388c677c1ecb"
    ports:
      - 2345:2345
      - 8040:8040
      - 8080:8080
    volumes: 
      - ./data/ml-25m:/data/csv/
  worker:
    build: 
      context: src/PC4
      dockerfile: Dockerfile
    environment:
      WORKER_TYPE: "worker"
      ORCHESTRATOR_IP: "orchestrator:8040"
      #ORCHESTRATOR_IP: "10.0.0.13:8040"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: default
    ports:
      - 27017:27017
    volumes: 
      - ./data/mongo:/data/db/

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  frontend:
    container_name: frontend
    build: 
      context: src/PC4/frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: "http://10.0.0.13:8080"
      VITE_TMDB_KEY: "6cffcef37c0b20c814c8de16da046284"
      VITE_TMDB_BEARER: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2Y2ZmY2VmMzdjMGIyMGM4MTRjOGRlMTZkYTA0NjI4NCIsIm5iZiI6MTc2NDczNDcwNC45MzUwMDAyLCJzdWIiOiI2OTJmYjZmMDE5OTUyNzIxZWVjOTVlODQiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.DRc1bGqk0O0E0Vvzl0PfyZ9_9ZrCiNkiG9-F0H33fHM"
    ports:
      - 5173:5173
volumes:
    cache:
      driver: local