services:
  orchestrator:
    build: 
      context: src/PC3
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: "mongodb://user:pass@mongo:27017/?authSource=admin"
      MOVIE_CSV_PATH:  "/data/csv/movies.csv"
      RATING_CSV_PATH: "/data/csv/ratings.csv"
      TAGS_CSV_PATH:   "/data/csv/tags.csv"
      LINKS_CSV_PATH:   "/data/csv/links.csv"
    ports:
      - 8080:8080
    volumes: 
      - ./data/ml-25m:/data/csv/


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: default
    ports:
      - 27017:27017
    volumes: 
      - ./data/mongo:/data/db/

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes:
    cache:
      driver: local